### ISSUE TITLE
【2022】CINN基础pass开发任务

### ISSUE THREAD

**Issue by SunNy820828449** [PaddlePaddle/CINN#1090]
Pass开发参考[文档](https://github.com/SunNy820828449/community/blob/cinn_pass_develop/pfcc/call-for-contributions/cinn_pass_develop.md)

任务清单
| 序号 | 任务名称 | 难度  | 状态 | 作者 | PR |
|:----: |:----:| :----:| :----: | :----: | :----: |
|1| **CSE(公共子表达式消除)** | 难 |   |  |
|2| **DCE(死代码消除)** | 中 |   |  |

**Comment by zrr1999** [comment]
认领 CSE(公共自表达式消除)

**Comment by luotao1** [comment]
合并到下方issue一起管理
- #1115
