### ISSUE TITLE
【2022】CINN开发任务跟踪

### ISSUE THREAD

**Issue by qlogcn** [PaddlePaddle/CINN#1115]
避免重复工作，这里登记任务情况，如有进行开发中的同学，请回复你要开发的任务，这里定期更新情况。
### 基础算子开发任务清单 （7 / 7）
[参考文档](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/CINN/CINN_base_operator.md) mentor by @thisjiang 

| 序号 | 任务名称 | 难度  | 状态 | 作者 | PR |
|:----: |:----:| :----:| :----: | :----: | :----: |
|1| reciprocal（取倒数） |简单| **已完成**✅| [enkilee](https://github.com/enkilee) | https://github.com/PaddlePaddle/CINN/pull/1069
|2| cbrt（立方根） |简单| **已完成** ✅| [huangjiyi](https://github.com/huangjiyi) | https://github.com/PaddlePaddle/CINN/pull/1073
|3| logical_right_shift（逻辑右移） |简单| **已完成**✅ | [ccsuzzh](https://github.com/ccsuzzh) | https://github.com/PaddlePaddle/CINN/pull/1083
|4|clz |简单| **已完成**✅ | [zzk0](https://github.com/zzk0) | https://github.com/PaddlePaddle/CINN/pull/1059
|5| popc |简单| **已完成**✅ | [FisherWY](https://github.com/FisherWY) | https://github.com/PaddlePaddle/CINN/pull/1064
|6| atan2 |中等| **已完成**✅ | [zrr1999](https://github.com/zrr1999) | https://github.com/PaddlePaddle/CINN/pull/1058
|7|cholesky |困难| **已完成**✅ | @FisherWY | #1133 

### 中端pass开发任务清单 （1/1）
[参考文档](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/CINN/cinn_pass_develop.md) mentor by @SunNy820828449 

| 序号 | 任务名称 | 难度  | 状态 | 作者 | PR |
|:----: |:----:| :----:| :----: | :----: | :----: |
|1| **CSE(公共子表达式消除)** | 难 | **已完成** ✅（2023/02/16）  | @zrr1999  | #1116 #1166

### 调度原语开发任务清单 （4/4）
[参考文档](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/CINN/CINN_ir_schedule.md) mentor by @CtfGo 

| 序号 | 任务名称 | 难度  | 状态 | 作者 | PR |
|:----: |:----:| :----:| :----: | :----: | :----: |
|1|  Unannotate | 简单 |  已完成（2023/01/03）✅ | @AndPuQing   | #1126  |
|2| GetChildBlocks| 简单 | 已完成（2023/02/02）✅   | @ccsuzzh   | #1157  |
|3| SampleCategorica | 简单 |  已完成（2023/03/31）✅  | @enkilee   | #1169  |
|4| SamplePerfectTile | 中等 |  已完成（2023/01/17）✅ | @AndPuQing    | #1142  |

**Comment by qlogcn** [comment]
认领任务：resize

**Comment by longranger2** [comment]
认领任务:negate(取相反数)

**Comment by enkilee** [comment]
reciprocal（取倒数）

**Comment by huangjiyi** [comment]
认领任务：3. cbrt（立方根）

**Comment by ccsuzzh** [comment]
认领任务：logical_right_shift（逻辑右移）

**Comment by zrr1999** [comment]
认领：atan2

**Comment by zzk0** [comment]
认领：clz （其他小伙伴也可以继续认领）

- cholesky 这个算子可以参考看看 paddle 怎么实现的，paddle 用第三方库来实现的，如果在 CINN 中引入第三方库，做法应该是类似的

**Comment by FisherWY** [comment]
认领: 6 popc

**Comment by longranger2** [comment]
认领：bitcast_convert

**Comment by zzk0** [comment]
认领：cholesky
（赶其他项目，放弃了，抱歉😰；具体实现，可以参考看看 paddle 怎么实现的，paddle 用第三方库来实现的，如果在 CINN 中引入第三方库，做法应该是类似的）

**Comment by zrr1999** [comment]
认领：triangular_solve

**Comment by FisherWY** [comment]
认领：cholesky

**Comment by MayYouBeProsperous** [comment]
认领：中端pass开发任务2 DCE(死代码消除)

**Comment by MayYouBeProsperous** [comment]
认领：中端pass开发任务2 DCE(死代码消除)

**Comment by zrr1999** [comment]
认领：调度原语开发 Unannotate

**Comment by ccsuzzh** [comment]
认领：调度原语开发 GetChildBlocks

**Comment by enkilee** [comment]
mark:调度原语开发 SampleCategorica
Sorry ,old PR not using rand_seed, so I create new PR as follow:
https://github.com/PaddlePaddle/CINN/pull/1270

**Comment by zrr1999** [comment]
认领：调度原语开发 ReverseComputeInline

**Comment by AndPuQing** [comment]
认领：调度原语开发 SamplePerfectTile

**Comment by luotao1** [comment]
CINN 开发任务已经全部完成，感谢参与的小伙伴们！

> @enkilee (2) @huangjiyi (1) @ccsuzzh (2) @zzk0 (1) @FisherWY (2) @zrr1999 (2) @AndPuQing (2)

欢迎继续参与[快乐开源的其他任务](https://github.com/PaddlePaddle/Paddle/issues/48019)！
