### ISSUE TITLE
编译报错 libcinnapi.so

### ISSUE THREAD

**Issue by wangqiang9** [PaddlePaddle/CINN#1214]
参考教程：https://paddlepaddle.github.io/CINN/guide.html 和 https://paddlepaddle.github.io/CINN/tutorials/index.html 
然后编译并运行demo报错：
`./demo: error while loading shared libraries: libcinnapi.so: cannot open shared object file: No such file or directory`

**Comment by XDUWQ** [comment]
之前的编译 `bash ./build.sh ci` 的结果：
`======================================================================
FAIL: test_check_results (__main__.TestReciprocalCase1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/CINN/CINN/python/tests/ops/test_reciprocal_op.py", line 48, in test_check_results
    self.check_outputs_and_grads()
  File "/CINN/CINN/python/tests/ops/op_test.py", line 104, in check_outputs_and_grads
    max_relative_error, all_equal, equal_nan, "Outputs")
  File "/CINN/CINN/python/tests/ops/op_test.py", line 211, in check_results
    self.assertTrue(is_allclose, msg=error_message)
AssertionError: False is not true : [Check Outputs] [CPU] The 0-th output: total 32 different results, offset=0, shape=(32,), 0.000000e+00 vs 7.132941e+01, maximum_relative_diff=inf (absolute_diff=7.132941e+01).

======================================================================
FAIL: test_check_results (__main__.TestReciprocalCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/CINN/CINN/python/tests/ops/test_reciprocal_op.py", line 48, in test_check_results
    self.check_outputs_and_grads()
  File "/CINN/CINN/python/tests/ops/op_test.py", line 104, in check_outputs_and_grads
    max_relative_error, all_equal, equal_nan, "Outputs")
  File "/CINN/CINN/python/tests/ops/op_test.py", line 211, in check_results
    self.assertTrue(is_allclose, msg=error_message)
AssertionError: False is not true : [Check Outputs] [CPU] The 0-th output: total 10 different results, offset=0, shape=(10,), 0.000000e+00 vs 1.075237e+00, maximum_relative_diff=inf (absolute_diff=1.075237e+00).

======================================================================
FAIL: test_check_results (__main__.TestReciprocalCase3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/CINN/CINN/python/tests/ops/test_reciprocal_op.py", line 48, in test_check_results
    self.check_outputs_and_grads()
  File "/CINN/CINN/python/tests/ops/op_test.py", line 104, in check_outputs_and_grads
    max_relative_error, all_equal, equal_nan, "Outputs")
  File "/CINN/CINN/python/tests/ops/op_test.py", line 211, in check_results
    self.assertTrue(is_allclose, msg=error_message)
AssertionError: False is not true : [Check Outputs] [CPU] The 0-th output: total 10 different results, offset=0, shape=(1, 10), 0.000000e+00 vs 1.194706e+00, maximum_relative_diff=inf (absolute_diff=1.194706e+00).

======================================================================
FAIL: test_check_results (__main__.TestReciprocalOp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/CINN/CINN/python/tests/ops/test_reciprocal_op.py", line 48, in test_check_results
    self.check_outputs_and_grads()
  File "/CINN/CINN/python/tests/ops/op_test.py", line 104, in check_outputs_and_grads
    max_relative_error, all_equal, equal_nan, "Outputs")
  File "/CINN/CINN/python/tests/ops/op_test.py", line 211, in check_results
    self.assertTrue(is_allclose, msg=error_message)
AssertionError: False is not true : [Check Outputs] [CPU] The 0-th output: total 32 different results, offset=0, shape=(32,), 0.000000e+00 vs 1.340948e+00, maximum_relative_diff=inf (absolute_diff=1.340948e+00).

----------------------------------------------------------------------
Ran 4 tests in 4.816s

FAILED (failures=4)

174/181 Test #177: tests/ops/test_subtract_op ..............   Passed    2.95 sec
175/181 Test #178: tests/ops/test_sum_op ...................   Passed    2.67 sec
176/181 Test #179: tests/ops/test_transpose_op .............   Passed    2.52 sec
177/181 Test #180: tests/ops/test_unary_elementwise_op .....   Passed    2.56 sec
178/181 Test #181: tests/ops/test_uniform_random_op ........   Passed    2.58 sec
179/181 Test #176: tests/ops/test_squeeze_op ...............   Passed    7.53 sec
180/181 Test   #1: test_auto_tuner .........................   Passed   67.97 sec
181/181 Test #120: test02_matmul_case ......................   Passed  113.88 sec

99% tests passed, 2 tests failed out of 181

Total Test time (real) = 123.51 sec

The following tests FAILED:
        134 - test_broadcast_to_op (Failed)
        164 - tests/ops/test_reciprocal_op (Failed)
Errors while running CTest`

**Comment by wangqiang9** [comment]
已解决！
